# This will generate a token you can use to login to Argo workflow
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-server.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-workflows-server
type: kubernetes.io/service-account-token