apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-server
  namespace: etl-pipelines
rules:
  - apiGroups:
      - argoproj.io
      - ""
    resources:
      - workflows
      - workflowtaskresults
      - pods
      - cronworkflows
    verbs:
      - create
      - patch
      - get 
      - watch 
  - apiGroups:
      - argoproj.io
      - ""
    resources:
      - pods/log
      - cronworkflows
      - workflows
    verbs:
      - get 
      - watch 
      - patch