services:
  amd64:
    dockerfile: workloads/custom_containers/hardware_monitoring/amd64/Dockerfile
    image: markhamlee/amd64
    path: workloads/custom_containers/hardware_monitoring/amd64
    version: 2.1.2
  amdcpu_nvidiagpu:
    dockerfile: workloads/custom_containers/hardware_monitoring/amdcpu_nvidiagpu/Dockerfile
    image: markhamlee/amdcpu_nvidiagpu
    path: workloads/custom_containers/hardware_monitoring/amdcpu_nvidiagpu
    version: 2.1.2
  intel_x86:
    dockerfile: workloads/custom_containers/hardware_monitoring/intel_x86/Dockerfile
    image: markhamlee/intel_x86
    path: workloads/custom_containers/hardware_monitoring/intel_x86
    version: 2.1.3
  intel_x86_nvidia_gpu:
    dockerfile: workloads/custom_containers/hardware_monitoring/intel_x86_nvidia_gpu/Dockerfile
    image: markhamlee/intel_x86_nvidia_gpu
    path: workloads/custom_containers/hardware_monitoring/intel_x86_nvidia_gpu
    version: 2.1.2
  raspberrypi5:
    dockerfile: workloads/custom_containers/hardware_monitoring/raspberrypi5/Dockerfile
    image: markhamlee/raspberrypi5
    path: workloads/custom_containers/hardware_monitoring/raspberrypi5
    version: 1.0.5
  raspberrypi_4b:
    dockerfile: workloads/custom_containers/hardware_monitoring/raspberrypi_4b/Dockerfile
    image: markhamlee/raspberrypi_4b
    path: workloads/custom_containers/hardware_monitoring/raspberrypi_4b
    version: 1.8.3
  rockchip3588:
    dockerfile: workloads/custom_containers/hardware_monitoring/rockchip3588/Dockerfile
    image: markhamlee/rockchip3588
    path: workloads/custom_containers/hardware_monitoring/rockchip3588
    version: 1.8.4
  technitium_monitoring:
    dockerfile: workloads/custom_containers/network_monitoring/technitium_monitoring/Dockerfile
    image: markhamlee/technitium_monitoring
    path: workloads/custom_containers/network_monitoring/technitium_monitoring
    version: 1.4.2
