---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joplin-server
  name: joplin-server
  namespace: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: joplin-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 70
              preference:
                matchExpressions:
                  - key: k3s_role
                    operator: In
                    values:
                    - data_node
            - weight: 30
              preference:
                matchExpressions:
                  - key: agent_type
                    operator: In
                    values:
                    - x86_worker
      containers:
        - name: joplin
          image: joplin/server:latest
          imagePullPolicy: Always
          env:
            - name: APP_PORT
              value: '22300'
            - name: APP_BASE_URL
              value: https://joplin.local.markhamslab.com
            - name: DB_CLIENT
              value: pg
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-data
                  optional: false 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-data
                  optional: false 
            - name: POSTGRES_DATABASE
              value: joplin
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: postgres-db-port
                  name: postgres-data
                  optional: false  
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: postgres-db-host
                  name: postgres-data
                  optional: false
            - name: MAILER_ENABLED
              value: '0'
            # - name: MAILER_HOST
            #  value: ""
            # - name: MAILER_PORT
            #  value: ""
            # - name: MAILER_SECURE
            #  value: '0'
            # - name: MAILER_AUTH_USER
            #  value: ""
            # - name: MAILER_AUTH_PASSWORD
            #  value: ""
            # - name: MAILER_NOREPLY_NAME
            #   value: ""
            # - name: MAILER_NOREPLY_EMAIL
            #  value: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: joplin-server
  name: joplin-server
  namespace: joplin
spec:
  ports:
    - name: joplin-server
      port: 22300
      targetPort: 22300
      # targetPort: http
      protocol: TCP
  selector:
    app: joplin-server
  type:
    ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: joplin-server
  namespace: joplin
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: joplin.local.example.com
      http:
        paths:
          - backend:
              service:
                name: joplin-server
                port:
                  number: 22300
            path: /
            pathType: Prefix