services:
  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    hostname: grafana
    restart: unless-stopped

    environment:
      GF_SERVER_ROOT_URL: "https://sa-data-node0.tail8077cf.ts.net/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

    volumes:
      - /home/admin/.app_data/grafana/data:/var/lib/grafana

    networks:
      - proxy

    security_opt:
      - no-new-privileges:true

    # Commenting out the items below allows the service to use the ingress properly 
    # without endless redirect loops
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`tailscale_server_url.ts.net`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=tsresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true