apiVersion: v2
name: redis
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: redis
  version: 19.6.1
  repository: oci://registry-1.docker.io/bitnamicharts
  alias: redis
  condition: redis.enabled