adminUser:
  bucket: default
  organization: your org name 
  password: ''
  retention_policy: 0s
  token: ''
  user: admin
affinity: {}
env: {}
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: influxdb
  tag: 2.3.0-alpine
ingress:
  annotations: {}
  enabled: true
  hostname: influxdb.local.example.com
  path: /
  tls: false
  class: traefik  # had to add this to the original yaml for it to install/run
initScripts:
  enabled: false
  scripts:
    init.sh: >+
      #!/bin/bash

      influx apply --force yes -u
      https://raw.githubusercontent.com/influxdata/community-templates/master/influxdb2_operational_monitoring/influxdb2_operational_monitoring.yml

livenessProbe: {}
nameOverride: ''
nodeSelector: {}
pdb:
  create: true
  minAvailable: 1
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  mountPath: /var/lib/influxdb2
  size: 50Gi
  subPath: ''
podAnnotations: {}
podLabels: {}
readinessProbe: {}
resources: {}
securityContext: {}
service:
  annotations: {}
  labels: {}
  port: 80
  portName: http
  targetPort: 8086
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: null
startupProbe:
  enabled: false
tolerations: null