apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-server
  namespace: etl-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-server
subjects:
- kind: ServiceAccount
  name: argo-workflows-server