apiVersion: v2
name: postgresql
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: 15.5.14
  repository: oci://registry-1.docker.io/bitnamicharts
  alias: postgresql
  condition: postgresql.enabled
