apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: '2023-12-01T03:11:36Z'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    recurring-job-group.longhorn.io/default: enabled
    recurring-job.longhorn.io/12-hour-backup: enabled
  name: mosquitto
  namespace: eclipse-mosquitto
  uid: 3ed33121-d300-4716-94c8-e901bd56aaa8
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-3ed33121-d300-4716-94c8-e901bd56aaa8
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  phase: Bound