apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  creationTimestamp: '2023-12-01T03:11:36Z'
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    helm.sh/chart: mosquitto-2.4.1
  name: mosquitto
  namespace: eclipse-mosquitto
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mqtt
      nodePort: 30126
      port: 1883
      protocol: TCP
      targetPort: mqtt
    - name: websocket
      nodePort: 31489
      port: 9090
      protocol: TCP
      targetPort: websocket
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  sessionAffinity: None
  type: LoadBalancer