apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: mosquitto
    meta.helm.sh/release-namespace: eclipse-mosquitto
  creationTimestamp: '2023-12-01T03:11:36Z'
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
    helm.sh/chart: mosquitto-2.4.1
  name: mosquitto
  namespace: eclipse-mosquitto
  uid: b3bcf0df-9d53-47c2-8bb9-59872a8f7967