apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: mosquitto
    meta.helm.sh/release-namespace: eclipse-mosquitto
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
    helm.sh/chart: mosquitto-2.4.1
    node_type: arm64_worker
  name: mosquitto
  namespace: eclipse-mosquitto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
      namespace: eclipse-mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:2.0.18
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: websocket
            timeoutSeconds: 1
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
            - containerPort: 9090
              name: websocket
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: websocket
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 128Mi
            requests:
              cpu: 150m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: config
              subPath: mosquitto.conf
            - mountPath: /mosquitto/data
              name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        node_type: arm64_worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mosquitto
      serviceAccountName: mosquitto
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto