apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: mosquitto
    meta.helm.sh/release-namespace: eclipse-mosquitto
  labels:
    app.kubernetes.io/instance: mosquitto
    helm.sh/chart: mosquitto-2.4.1
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: eclipse-mosquitto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mosquitto
      app.kubernetes.io/name: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mosquitto
        app.kubernetes.io/name: mosquitto
      namespace: eclipse-mosquitto
    spec:
      containers:
        - image: eclipse-mosquitto:1.6.12
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: websocket
            timeoutSeconds: 1
          name: mosquitto
          ports:
            - containerPort: 1883
              name: mqtt
              protocol: TCP
            - containerPort: 9090
              name: websocket
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: websocket
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mosquitto/config/mosquitto.conf
              name: config
              subPath: mosquitto.conf
            - mountPath: /mosquitto/data
              name: data
      dnsPolicy: ClusterFirst
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: k3s_role
                  operator: In
                  values:
                    - agent
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: agent_type
                    operator: In
                    values:
                    - x86_tasks
            - weight: 20
              preference:
                matchExpressions:
                  - key: node_type
                    operator: In
                    values:
                    - x86_worker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mosquitto
      serviceAccountName: mosquitto
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: mosquitto
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto