apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-x86-node0
  namespace: operations
spec:
  selector:
    matchLabels:
      app: intel-x86-node0
  replicas: 1
  template:
    metadata:
      labels:
        app: intel-x86-node0
    spec:
      nodeName: node0
      containers:
        - name: 'intel-node'
          image: 'markhamlee/k3s-intel-node:latest' 
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          env:
            - name: MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-prod-secret
                  optional: false
            - name: MQTT_SECRET
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-prod-secret
                  optional: false
            - name: MQTT_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER
                  name: mqtt-config-data
                  optional: false
            - name: MQTT_PORT
              valueFrom:
                configMapKeyRef:
                  key: MQTT_PORT
                  name: mqtt-config-data
                  optional: false
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  key: X86_WORKER_NODE0_TOPIC
                  name: mqtt-config-data
                  optional: false
            - name: INTERVAL
              value: '2'
            - name: DEVICE_ID
              value: intelx86-worker-node0
      imagePullSecrets: 
        - name: private-docker-repo
      restartPolicy: Always
