# Leverages an Umbrella chart in the repo to pull in the Helm chart
# and then override values via a values.yaml chart in the same repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafanamkii
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: apps
  source:
    path: grafana/
    repoURL: https://github.com/MarkhamLee/k3s-iac-data-iot-platform.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml