# and then override values via a values.yaml chart in the same repo.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: loki-stack
  project: apps
  source:
    path: loki-grafana
    repoURL: https://github.com/MarkhamLee/k3s-iac-data-iot-platform.git
    targetRevision: HEAD
    helm:
      releaseName: loki
      valueFiles:
      - values.yaml