apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: apps
  source:
    path: traefik/
    repoURL: https://github.com/MarkhamLee/k3s-iac-data-iot-platform.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml