services:
  traefik:
    image: traefik:v3.6.13
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      # Simple/robust: bind on all addresses
      - "80:80"
      - "443:443"
      - "8082:8082"
      # or, if you really want to scope it, bind to 127.0.0.1 and
      # let Tailscale+iptables forward, but don’t hard-code 100.x.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/admin/Documents/GitHub/iac-repo-name/tailscale-server-name/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/admin/.app_data/traefik/traefik-logs:/var/log/traefik
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--entrypoints.metrics.address=:8082"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addserviceslabels=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.tsresolver.tailscale=true"
    labels:
      - "traefik.enable=true"

      # HTTP → HTTPS redirect
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`your-server-tailscale-url.ts.net`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      # HTTPS dashboard/API
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`your-server-tailscale-url.ts.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_CREDS_UPDATED}"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=tsresolver"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true