apiVersion: v2
name: loki
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: loki-stack
  version: 2.10.2
  repository: https://grafana.github.io/helm-charts
  alias: lokistack
  condition: lokistack.enabled