apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangepi_five_plus_monitoring
  namespace: operations
spec:
  selector:
    matchLabels:
      app: orangepi_five_plus_monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: orangepi_five_plus_monitoring
    spec:
      containers:
        - name: orangepi_five_plus_node0
          image: <your image repo here>
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: INFLUX_KEY
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-etl-variables
            - name: TABLE
              value: opi5_node0
            - name: INTERVAL
              value: '2'
      imagePullSecrets: 
        - name: docker-creds
    restartPolicy: Always
