apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangepi5-plus-node0-monitoring
  namespace: operations
spec:
  selector:
    matchLabels:
      app: orangepi5-plus-node0-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: orangepi5-plus-node0-monitoring
    spec:
      nodeName: orangepi5plus-node0
      containers:
        - name: 'orangepi-five-plus-node-zero'
          image: 'markhamlee/rc3588_monitoring' 
          imagePullPolicy: Always
          resources:
            limits:
              # raised cpu limit as I was getting CPU throttling alerts despite CPU util not going above 5%
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          env:
            - name: TOKEN 
              valueFrom:
                secretKeyRef:
                  key: PROD_INFLUX_KEY
                  name: influxdb-secret
                  optional: false 
            - name: ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_ORG
                  name: key-ops-variables
            - name: URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUX_URL
                  name: key-ops-variables
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: HARDWARE_BUCKET
                  name: key-ops-variables
            - name: TABLE
              value: opi5_node0
            - name: INTERVAL
              value: '2'
      imagePullSecrets: 
        - name: private-docker-repo
      restartPolicy: Always
