apiVersion: apps/v1
kind: Job
metadata:
  name: postgres-cat-facts-test-v2
  annotations:
    batch.kubernetes.io/job-tracking: ''
  namespace: etl-pipelines
spec:
  backoffLimit: 1
  completionMode: NonIndexed
  template:
    metadata:
      labels:
        job-name: postgres-cat-facts-test-v2
      namespace: etl-pipelines
    spec:
      containers:
        - name: cat-facts-test
          image: markhamlee/catfacts_postgres:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres-secrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secrets
          - name: ALERT_WEBHOOK
            valueFrom:
              secretKeyRef:
                key: WEBHOOK_ETL_ALERTS
                name: slack-webhook-pipeline-failures
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_TEST_DB
                name: test-etl-variables
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_DB_HOST
                name: key-etl-variables
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                key: POSTGRES_PORT
                name: key-etl-variables
          - name: CAT_TABLE
            valueFrom:
              configMapKeyRef:
                key: CAT_TABLE
                name: test-etl-variables
      imagePullSecrets: 
        - name: docker-creds
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30