apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-mki
  namespace: airflow
  labels:
    app: airflow-logs-mki
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi