auth:
  existingSecret: ''
  fernetKey: '' # generate a key and place it here 
  password: ''
  secretKey: ''
  username: 'user' # insert your own user name 
clusterDomain: cluster.local 
commonAnnotations: {}
commonLabels: {}
configuration: ''
dags:
  existingConfigmap: ''
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets:
      - dockersecrets
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r94
diagnosticMode:
  args:
    - infinity
  command:
    - sleep
  enabled: false
executor: CeleryExecutor
existingConfigmap: ''
externalDatabase:
  database: bitnami_airflow
  existingSecret: ''
  existingSecretPasswordKey: ''
  host: localhost
  password: ''
  port: 5432
  user: bn_airflow
externalRedis:
  existingSecret: ''
  existingSecretPasswordKey: ''
  host: localhost
  password: ''
  port: 6379
  username: ''
extraDeploy: []
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''
extraEnvVarsSecrets: []
extraVolumeMounts: []
extraVolumes: []
fullnameOverride: ''
git:
  clone:
    args: []
    command: []
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: '<name of your personal access token secret>'
    extraVolumeMounts: []
    resources: {}
  dags:
    enabled: true
    repositories:
      - branch: main
        name: repo_name
        path: /dags
        # Personal access tokens seem to work better with this helm chart (for me anyway)
        # Just go to your GitHub: settings --> Developer Settings --> Fine Grained Personal Access Tokens
        # name of the secret in the EnvVarsSecret and secret's key below 
        # Note: only necessary if you're synching a private repo and/or want to avoid "free account" rate limits
        repository: https://<your_github_username>:${key for your secret}@github.com/username/your_repo.git
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets:
      - dockersecrets # insert what you named your Docker secrets
    registry: docker.io
    repository: bitnami/git
    tag: 2.43.0-debian-11-r5
  plugins:
    enabled: false
    repositories:
      - branch: ''
        name: ''
        path: ''
        repository: ''
  sync:
    args: []
    command: []
    extraEnvVars: []
    extraEnvVarsCM: ''
    extraEnvVarsSecret: '<name of your personal access token secret>'
    extraVolumeMounts: []
    interval: 300
    resources: {}
global:
  imagePullSecrets:
    - dockersecrets
  imageRegistry: docker.io
  storageClass: ''
  cattle:
    systemProjectId: p-6scsz
ingress:
  annotations: {}
  apiVersion: ''
  enabled: false
  extraHosts: []
  extraPaths: []
  extraRules: []
  extraTls: []
  hostname: airflow.local
  ingressClassName: ''
  path: /
  pathType: ImplementationSpecific
  secrets: []
  selfSigned: false
  tls: false
initContainers: []
kubeVersion: ''
ldap:
  basedn: dc=example,dc=org
  binddn: cn=admin,dc=example,dc=org
  bindpw: ''
  enabled: false
  rolesMapping: >-
    { "cn=All,ou=Groups,dc=example,dc=org": ["User"],
    "cn=Admins,ou=Groups,dc=example,dc=org": ["Admin"], }
  rolesSyncAtLogin: 'True'
  searchAttribute: cn
  tls:
    CAFilename: ''
    allowSelfSigned: true
    certificatesMountPath: /opt/bitnami/airflow/conf/certs
    certificatesSecret: ''
    enabled: false
  uri: ldap://ldap_server:389
  userRegistration: 'True'
  userRegistrationRole: Public
loadExamples: false
metrics:
  affinity: {}
  automountServiceAccountToken: false
  containerPorts:
    http: 9112
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    privileged: false
    runAsNonRoot: true
    runAsUser: 1001
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
  enabled: false
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  hostAliases: []
  image:
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/airflow-exporter
    tag: 0.20220314.0-debian-11-r443
  lifecycleHooks: {}
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    supplementalGroups: []
    sysctls: []
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.service.ports.http }}'
      prometheus.io/scrape: 'true'
    clusterIP: ''
    ports:
      http: 9112
    sessionAffinity: None
  serviceMonitor:
    enabled: false
    honorLabels: false
    interval: ''
    jobLabel: ''
    labels: {}
    metricRelabelings: []
    namespace: ''
    relabelings: []
    scrapeTimeout: ''
    selector: {}
  tolerations: []
nameOverride: ''
postgresql:
  architecture: standalone
  auth:
    database: bitnami_airflow
    enablePostgresUser: true
    existingSecret: ''
    password: ''
    username: bn_airflow
  enabled: true
rbac:
  create: true
  rules: []
redis:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: ''
    password: ''
  enabled: true
scheduler:
  affinity: {}
  args: []
  automountServiceAccountToken: true
  command: []
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    privileged: false
    runAsNonRoot: true
    runAsUser: 1001
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraEnvVarsSecrets: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/airflow-scheduler
    tag: 2.8.0-debian-11-r1
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  pdb:
    create: false
    maxUnavailable: ''
    minAvailable: 1
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    supplementalGroups: []
    sysctls: []
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  sidecars: []
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
service:
  annotations: {}
  clusterIP: ''
  externalTrafficPolicy: Cluster
  extraPorts: []
  loadBalancerIP: ''
  loadBalancerSourceRanges: []
  nodePorts:
    http: ''
  ports:
    http: 8080
  sessionAffinity: None
  sessionAffinityConfig: {}
  type: ClusterIP
serviceAccount:
  annotations: {}
  automountServiceAccountToken: true
  create: true
  name: ''
sidecars: []
web:
  affinity: {}
  args: []
  automountServiceAccountToken: false
  baseUrl: ''
  command: []
  containerPorts:
    http: 8080
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    privileged: false
    runAsNonRoot: true
    runAsUser: 1001
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  existingConfigmap: ''
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraEnvVarsSecrets: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.8.0-debian-11-r2
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  pdb:
    create: false
    maxUnavailable: ''
    minAvailable: 1
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    supplementalGroups: []
    sysctls: []
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
worker:
  affinity: {}
  args: []
  automountServiceAccountToken: true
  autoscaling:
    enabled: false
    maxReplicas: 3
    minReplicas: 1
    targetCPU: 80
    targetMemory: 80
  command: []
  containerPorts:
    http: 8793
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    enabled: true
    privileged: false
    runAsNonRoot: true
    runAsUser: 1001
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraEnvVars: []
  extraEnvVarsCM: ''
  extraEnvVarsSecret: ''
  extraEnvVarsSecrets: []
  extraVolumeClaimTemplates: []
  extraVolumeMounts: []
  extraVolumes: []
  hostAliases: []
  image:
    debug: false
    digest: ''
    pullPolicy: IfNotPresent
    pullSecrets: []
    registry: docker.io
    repository: bitnami/airflow-worker
    tag: 2.8.0-debian-11-r1
  initContainers: []
  lifecycleHooks: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 180
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 5
  nodeAffinityPreset:
    key: ''
    type: ''
    values: []
  nodeSelector: {}
  pdb:
    create: false
    maxUnavailable: ''
    minAvailable: 1
  podAffinityPreset: ''
  podAnnotations: {}
  podAntiAffinityPreset: soft
  podLabels: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    fsGroupChangePolicy: Always
    supplementalGroups: []
    sysctls: []
  podTemplate: {}
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  replicaCount: 1
  resources:
    limits: {}
    requests: {}
  schedulerName: ''
  sidecars: []
  startupProbe:
    enabled: false
    failureThreshold: 15
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: ''
  tolerations: []
  topologySpreadConstraints: []
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate