nodered:
  namespace: node-red
  replicas: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: k3s_role
              operator: In
              values:
                - agent
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: agent_type
                operator: In
                values:
                - x86_tasks
        - weight: 20
          preference:
            matchExpressions:
              - key: node_type
                operator: In
                values:
                - x86_worker
  deploymentStrategy: "RollingUpdate"
  image: 
    registry: docker.io
    # -- The image repository to pull from
    repository: nodered/node-red
    # -- The image pull policy
    pullPolicy: IfNotPresent
    # -- The image tag to pull, default: `Chart.appVersion`
    tag: "4.0.1"
  fullnameOverride: node-red
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

  persistence:
    enabled: true
    # -- Type of persistent volume claim
    storageClass: "longhorn"
    # -- Use an existing PVC to persist data
    existingClaim: "pvc-2c5a1bfa-4f82-4b6f-a43c-fe90cd063f00"
    # -- Persistence access mode
    accessMode: ReadWriteOnce
    # -- Size of persistent volume claim
    size: 5Gi
    # -- ## Keep a created Persistent volume claim when uninstalling the helm chart (default: false)
    keepPVC: true

  ingress:
    # -- Enable an ingress resource for the server
    enabled: true
    # -- Defines which ingress controller will implement the resource
    className: traefik
    # -- Additional ingress annotations
    hosts:
      #  Ingress accepted hostnames
      - host: nodered.local.markhamslab.com
        paths:
            # -- The base path
          - path: /
            # --  Ingress type of path
            pathType: ImplementationSpecific
        port:
          number: 1880
        service:
          name: node-red
    # --  Ingress TLS configuration
    tls: []
    status:
      loadBalancer:
        ingress:
          - hostname:
              nodered.local.markhamslab.com