name: amd5560u_monitoring_image_build

on:
  push:
    branches:
      - "main"
    paths:
      - "hardware_monitoring/amd_5560u/*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./hardware_monitoring/amd_5560u/
          file: ./hardware_monitoring/amd_5560u/Dockerfile
          platforms: linux/amd64
          push: true
          tags: markhamlee/amd5560monitoring:latest