name: amdcpu_nvidia_gpu_monitoring_image_build

on:
  push:
    branches:
      - "main"
    paths:
      - "hardware_monitoring/amdcpu_nvidiagpu/*"
      - "hardware_monitoring/hw_monitoring_libraries/*"
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./hardware_monitoring/
          file: ./hardware_monitoring/amdcpu_nvidiagpu/Dockerfile
          platforms: linux/amd64
          push: true
          tags: markhamlee/amdcpu_nvidia_monitoring:latest